# Generated by Django 3.2 on 2022-01-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='currency_type',
            field=models.CharField(max_length=255),
        ),
    ]
