# Generated by Django 3.2 on 2022-01-19 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_alter_students_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='alternate_mobile',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='prn_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
