# Generated by Django 3.2 on 2022-01-19 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20220119_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdocument',
            old_name='other',
            new_name='other_doc_one',
        ),
        migrations.RemoveField(
            model_name='studentdocument',
            name='cc',
        ),
        migrations.AddField(
            model_name='collegedocument',
            name='other_comment_one',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collegedocument',
            name='other_comment_two',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collegedocument',
            name='other_documents_one',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collegedocument',
            name='other_documents_two',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='other_doc_three',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='other_doc_two',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='other_one_comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='other_three_comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='other_two_comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
